- name: deploy
  uses: garygrossgarten/github-action-scp@release
  needs: build
  with:
    local: ${{ secrets.DIST_LOCAL }}
    remote: ${{ secrets.DIST_REMOTE }}
    host: ${{ secrets.HOST }}
    username: ${{ secrets.SSH_USER }}
    password: ${{ secrets.PASSWORD }}
