name: Node.js CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  install-dependencies:
    strategy:
      matrix:
        node-version: [16.x]
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: npm install

  build:
    strategy:
      matrix:
        node-version: [16.x]
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Build project
        run: npm run build --if-present

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Build project
        run: npm run build --if-present
      - name: Deploy
        uses: garygrossgarten/github-action-scp@release
        with:
          local: dist
          remote: ${{ secrets.DIST_REMOTE }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
          rmRemote: true
