name: Node.js CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  install-dependencies:
    strategy:
      matrix:
        node-version: [16.x]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci --force

  build-josesaranda-web:
    strategy:
      matrix:
        node-version: [16.x]
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use cached node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Build project
        run: GH_TOKEN=${{secrets.GH_TOKEN}} npm run build:josesaranda-web --if-present

  build-habitatcss-web:
    strategy:
      matrix:
        node-version: [16.x]
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use cached node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Build project
        run: npm run build:habitatcss-web --if-present

  deploy-josesaranda-web:
    needs: [build-josesaranda-web]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use cached node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Build project
        run: GH_TOKEN=${{secrets.GH_TOKEN}} npm run build:josesaranda-web --if-present
      - name: Deploy
        uses: garygrossgarten/github-action-scp@release
        with:
          local: dist/packages/josesaranda-web
          remote: ${{ secrets.DIST_REMOTE }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
          rmRemote: true

  deploy-habitatcss-web:
    needs: [build-habitatcss-web]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use cached node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Build project
        run: GH_TOKEN=${{secrets.GH_TOKEN}} npm run build:habitatcss-web --if-present
      - name: Deploy
        uses: garygrossgarten/github-action-scp@release
        with:
          local: dist/packages/habitatcss-web
          remote: ${{ secrets.ROOT_REMOTE }}/habitatcss-web
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
          rmRemote: true
